import * as vscode from 'vscode';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { vinvHomeDir } from '../vinvHome';
import { getHarnessId, isMcpEnabled } from '../config/settings';
import { ENGINE_NAMES, getBinPath, enginesRoot } from '../tracelens/bin';
import { resolveBash } from '../proc';
import { detectTargets } from '../mcp/mcpRegistrar';

/**
 * Support bundle: engine logs, artifacts and config shape, exported for the
 * user to review and attach to a bug report. Vinv sends nothing anywhere —
 * the report is written to a file the user owns and explicitly shares.
 */

const MAX_LOG_TAIL = 20_000;

/** Reads the last N bytes of a text file; returns null when unreadable. */
function tail(file: string, bytes = MAX_LOG_TAIL): string | null {
	try {
		const stat = fs.statSync(file);
		const start = Math.max(0, stat.size - bytes);
		const fd = fs.openSync(file, 'r');
		try {
			const buf = Buffer.alloc(stat.size - start);
			fs.readSync(fd, buf, 0, buf.length, start);
			return (start > 0 ? `…(truncated, showing last ${bytes} bytes)…\n` : '') + buf.toString('utf8');
		} finally {
			fs.closeSync(fd);
		}
	} catch {
		return null;
	}
}

/** Lists a directory's entries with sizes and mtimes; empty when absent. */
function listDir(dir: string): string[] {
	try {
		return fs
			.readdirSync(dir)
			.map((name) => {
				try {
					const s = fs.statSync(path.join(dir, name));
					return `${name} — ${s.size} bytes, modified ${s.mtime.toISOString()}`;
				} catch {
					return name;
				}
			})
			.sort();
	} catch {
		return [];
	}
}

function section(title: string, body: string): string {
	return `\n## ${title}\n\n${body.trim() || '_(none)_'}\n`;
}

function fence(body: string, lang = ''): string {
	return `\`\`\`${lang}\n${body}\n\`\`\``;
}

/** Builds the diagnostic report. */
function buildReport(context: vscode.ExtensionContext, workspaceRoot: string | undefined): string {
	const home = vinvHomeDir();
	const lines: string[] = [];

	lines.push('# Vinv diagnostic report');
	lines.push('');
	lines.push(
		'Generated by **Vinv: Export Diagnostics**. Review this file before attaching it to a ' +
			'bug report — it contains log output from your machine, which may include ' +
			'file paths and error text from your project. It never contains source code.',
	);
	lines.push('');
	lines.push(`Generated: ${new Date().toISOString()}`);

	lines.push(
		section(
			'Environment',
			fence(
				[
					`extension_version: ${(context.extension.packageJSON as { version?: string }).version}`,
					`editor:            ${vscode.env.appName} ${vscode.version}`,
					`platform:          ${process.platform} ${process.arch} (${os.release()})`,
					`remote:            ${vscode.env.remoteName ?? 'local'}`,
					`dev_build:         ${context.extensionMode !== vscode.ExtensionMode.Production}`,
					`machine_id:        ${vscode.env.machineId}`,
					`session_id:        ${vscode.env.sessionId}`,
					`bash:              ${resolveBash() ?? 'NOT FOUND'}`,
					`workspace_open:    ${workspaceRoot ? 'yes' : 'no'}`,
				].join('\n'),
			),
		),
	);

	lines.push(
		section(
			'Configuration',
			fence(
				[
					`harness:      ${getHarnessId()}`,
					`mcp_enabled:  ${isMcpEnabled()}`,
					`engines_root: ${enginesRoot(context) ?? 'NOT FOUND'}`,
				].join('\n'),
			),
		),
	);

	// Engines: a missing binary is a top cause of "nothing happens".
	const bins = ENGINE_NAMES.map((name) => {
		const p = getBinPath(context, name);
		return `${name} — ${fs.existsSync(p) ? p : 'MISSING'}`;
	});
	lines.push(section('Engines', fence(bins.join('\n'))));

	let mcpTargets: string[] = [];
	try {
		mcpTargets = workspaceRoot ? detectTargets(workspaceRoot).map((t) => t.label) : [];
	} catch {
		mcpTargets = ['(detection failed)'];
	}
	lines.push(section('Detected agent tools', fence(mcpTargets.join('\n'))));

	if (workspaceRoot) {
		const vinvDir = path.join(workspaceRoot, '.vinv');
		lines.push(section('Workspace artifacts (.vinv)', fence(listDir(vinvDir).join('\n'))));

		// Engine logs — the actual failure output behind a discovery/bring-up error.
		const logDir = path.join(vinvDir, 'logs');
		for (const name of listDir(logDir).slice(0, 6)) {
			const file = path.join(logDir, name.split(' — ')[0]);
			const body = tail(file);
			if (body) {
				lines.push(section(`Log: ${name.split(' — ')[0]}`, fence(body)));
			}
		}
	}

	// The episode ledger: arms, rewards, verified/aborted outcomes per episode.
	const ledger = tail(path.join(home, 'telemetry', 'episodes.jsonl'), 40_000);
	if (ledger) {
		lines.push(section('Episode ledger (~/.vinv/telemetry/episodes.jsonl)', fence(ledger, 'json')));
	}

	return lines.join('\n');
}

/**
 * Writes the diagnostic report and opens it for the user to review before they
 * choose to share it. Returns the file path.
 */
export async function exportDiagnostics(context: vscode.ExtensionContext): Promise<void> {
	const workspaceRoot = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
	const report = buildReport(context, workspaceRoot);
	const dir = workspaceRoot ? path.join(workspaceRoot, '.vinv', 'reports') : os.tmpdir();
	fs.mkdirSync(dir, { recursive: true });
	const target = path.join(dir, `vinv-diagnostics-${Date.now()}.md`);
	fs.writeFileSync(target, report, 'utf8');

	const doc = await vscode.workspace.openTextDocument(vscode.Uri.file(target));
	await vscode.window.showTextDocument(doc, { preview: false });
	void vscode.window
		.showInformationMessage(
			'Vinv: Diagnostic report created. Review it, then attach it to your bug report.',
			'Reveal File',
		)
		.then((choice) => {
			if (choice === 'Reveal File') {
				void vscode.commands.executeCommand('revealFileInOS', vscode.Uri.file(target));
			}
		});
}
